# -*- coding: utf-8 -*-
"""ntscapper for Twitter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dmZadaAQiRqwcheFvVY1itOH8RRpP-zz

https://github.com/bocchilorenzo/ntscraper
"""

!pip install ntscraper

import json
import pandas as pd
import io
import sys
from ntscraper import Nitter
scraper = Nitter(log_level=1, skip_instance_check=False)
import nest_asyncio
nest_asyncio.apply()

github_hash_tweets = scraper.get_tweets("github", mode='hashtag', number=10)

terms = ["github", "bezos", "musk"]

results = scraper.get_tweets(terms, mode='term')

def process_text(text):
    # This function will call the Google Colab function via Uplink
    result = anvil.server.call('colab_process_text', text)
    return result

Bossman_tweets = scraper.get_tweets("0xBossman", mode='user', number=1)

# Normalize the 'tweets' part of the data
tweets_df = pd.json_normalize(Bossman_tweets['tweets'], max_level=2)
# tweets_df = tweets_df.transpose()

# Display the normalized DataFrame
# print(tweets_df)

# to save to csv
tweets_df.to_csv('tweets.csv')
pd.read_csv('tweets.csv')